spring:
  application:
    name: example-game
  main:
    allow-bean-definition-overriding: true
  autoconfigure:
    exclude:
      - org.springframework.boot.autoconfigure.mongo.MongoReactiveAutoConfiguration
  profiles:
    include:
      - db

#logging.level.root: DEBUG