spring:
  application:
    name: example-game
  main:
    allow-bean-definition-overriding: true
  autoconfigure:
    exclude:
      - org.springframework.boot.autoconfigure.mongo.MongoReactiveAutoConfiguration

#logging.level.root: DEBUG

play:
  hotswap:
    enabled: false
  repository:
    type: memory

rsocket:
  client:
    brokers:
#      - tcp://localhost:8888
    connectTimeout: 10s
    auth:
      type: token
      token: cWpC&amp;yK##K0bvCXd
